Controllers films users
elenabokhan13/java-filmorate pull request #10
Opened 2023-11-30 10:26 UTC by elenabokhan13

2023-12-01 04:14 UTC, elenabokhan13 commented
я не знала, что нужно в тот же пулл заливать новый коммит и закрыла его и сделала новый. 

я не поправила только аннотацию над name, я в том пуле отписалась, что по заданию, нам разрешается пустое имя, и если оно пустое, то нужно вместо имени использовать логин. поэтому я не валидирую имя, если я это делаю, то программа работает не так, и я не прохожу тесты на постмане. вот ссылка на первый пул с комментариями https://github.com/elenabokhan13/java-filmorate/pull/4

2023-12-01 19:16 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2023-12-01 19:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +        super();
Вы уже проходили эту тему. Что тут вы делаете? Зачем в конструктор передаете сообщение и дальше его не используете? Надо разобраться
Сообщение которое вы передаете в конструктор нужно также передавать в super

2023-12-01 19:16 UTC, Frilock commented on pom.xml
> +            <version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-12-01 19:16 UTC, Frilock commented on pom.xml
> +    <dependencies>
Пропустите одну строчку перед dependency, чтобы не сливалось

2023-12-01 19:16 UTC, Frilock commented on pom.xml
> +        <dependency>
Зачем вы подключаете эту библиотеку? Она используется?

2023-12-01 19:16 UTC, Frilock commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
Зачем вы подключаете эту библиотеку? Она используется?

2023-12-01 19:16 UTC, Frilock commented on pom.xml
> +            <groupId>org.hibernate.validator</groupId>
Зачем вы подключаете эту библиотеку? Она используется?

2023-12-01 19:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28", FORMATTER))) {
Вы в своем коде используете как валидацию с использованием аннотаций, так и самописную в данном методе. Только часть случаев у вас не покрывается. Что будет если film.getReleaseDate вернет null? или getDescription? На мой взгляд вы эти случаи не проверяете. Сделайте на них юнит тесты чтобы убедиться что все корректно

2023-12-01 19:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28", FORMATTER))) {
Вы тут указываете дату, а для описание максимальное число, в коде это выглядит как магические числа, поэтому их лучше вынести в константы класса.
Тут на ваше усмотрение

2023-12-01 19:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (userNew != null) {
Смотрите, вообще лучше инвертировать условие и внутри блока if бросать исключение, а остальной код уже писать без лишней вложенности.

На ваше усмотрение

2023-12-01 19:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Обе эти проверки можно обьединить в одну, для этого подключите библиотеку apache common 3, и используйте StringUtils.isBlank/isNotBlank

2023-12-01 19:16 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Разбейте данный тест на 2 тестовых класса, для каждого из контроллеров. Так они будут меньше и понятнее. 
На ваше усмотрение

2023-12-04 05:26 UTC, elenabokhan13 commented on pom.xml
> +        <dependency>
к сожалению, от этой и следующей библиотеки у меня не получается отказаться. в ТЗ не было прописано, что мы должны писать на 11 джаве и втором спинг буте. в итоге я все написала на 17 джаве и третьем спринг буте, а когда на гитхабе не проходила тесты, пришлось понизить. но после этого у меня не работает javax.validation.constraints, который по идее должен заменить jakarta для валидации. пришлось перерыть кучу инфы, чтобы понять, какие библиотеку подключить, чтобы снова заработало

если у вас есть советы, что делать в таких случаях, то буду очень благодарна

2023-12-04 05:45 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
о это очень круто!

2023-12-04 06:13 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28", FORMATTER))) {
код поправила, тесты дописала :) т.к. в ТЗ не указано явно, что при создании фильма обязательно должно быть описание и релиз дата, я добавила проверку на null, чтобы не вылетала ошибка в том, случае если их нет, а я к ним обращаюсь

2023-12-04 19:20 UTC, Frilock commented on pom.xml
> +        <dependency>
Хм, да, возможны нюансы, пойдет и так, просто обычно достаточно одной библиотеки

2023-12-04 19:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Там довольно много полезных функций, так же можно и проверять коллекции сразу на нул и на пустоту. Но там другая библиотечка

2023-12-04 19:21 UTC, Frilock approved these changes
Принято, идем дальше =)

2023-12-05 05:12 UTC, merged