feat: added friends and films likes
elenabokhan13/java-filmorate pull request #11
Opened 2023-12-11 13:08 UTC by elenabokhan13

2023-12-11 16:59 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2023-12-11 16:59 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NullPointerException("Данный фильм еще не добавлен в базу.");
Такие исключение не бросают

2023-12-11 16:59 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    private UserController userController;
Не очень понял, вы заинжектили бин, а больше его не используете. Почему?

2023-12-12 05:36 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NullPointerException();
спасибо, понятно, я сделала свое исключение. а RuntimeException мы можем пробрасывать сами или его тоже всегда нужно кастомизировать?

2023-12-12 08:39 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> filmsLiked;
у меня не получается инициализировать коллекции сразу. если я делаю = new HashSet<>(); то это ничего не дает, поле все равно получается null. если делать final или static, то тогда сет инициализируется сразу, но работает не так, как нужно мне. у каждого юзера должна создаваться своя уникальная пара этих сетов.

я даже пробовала вот так инициализировать, все равно получается null поле:
 {
        friends = new HashSet<>();
    }

поэтому оставила сеттинг этих коллекция при создании и апдейте объектов

2023-12-12 08:43 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    private UserController userController;
а в двух последних методах я обращаюсь к userController, без этого бина они не работают

2023-12-12 08:44 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Data
убрала ))

2023-12-12 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NullPointerException();
На мой взгляд, лучше кастомизировать

2023-12-12 16:39 UTC, Frilock requested changes
Добрый вечер, еще ряд комментариев, на ряд из них можете просто ответить, мне интересно почему именно так сделали

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +@Data
На самом деле было достаточно Getter, AllArgsConstructor

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ((user == null) || (film == null)) {
между || 1 условие, нет смысла обособлять его скобками - 
if (user == null || film == null) {

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .findFirst().orElseThrow(NullPointerException::new);
Опять же бросаете NPE, что не очень хорошая идея

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.getUsers().get(id);
А если не будут найдены?

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Long> userCopy = new HashSet<Long>(user.getFriends());
А зачем так сложно через копирование?

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .findFirst().orElseThrow(NullPointerException::new);
Бросок NPE

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private int filmId = 0;
static имелся ввиду к filmId, а вот к коллекции фильмов добавлять статик не очень идея, поскольку данная коллекция у вас будет меняться.

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            if (film.getDescription().length() > 200) {
2 ифа можно обьединить в один

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            if (film.getReleaseDate().isBefore(START_RELEASE_DATE)) {
2 ифа можно обьединить в 1

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (Objects.equals(film.getName(), "")) {
Лучше StringUtils.isBlank

2023-12-12 16:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private int userId = 0;
Аналогично - сюда статик а вот от коллекции users лучше убрать

2023-12-13 09:22 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .findFirst().orElseThrow(NullPointerException::new);
пропустила случаи со стримом, теперь все поправила

2023-12-13 09:26 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.getUsers().get(id);
пропустила эту проверку в этом и следующем методе, сейчас поправила

2023-12-13 09:50 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Long> userCopy = new HashSet<Long>(user.getFriends());
если я делаю вот так (без дип копи):
 Set<Long> userCopy = user.getFriends();
 userCopy.retainAll(friend.getFriends());

то у меня по сути получается ссылка на основной объект, и когда я вычитаю из одного сета другой (чтобы найти пересечения), то у меня из основного сета тоже вычитается значение. в результате, программа работает неверно. поэтому, чтобы вычитание сетов работало независимо, я сделала через такое копирование, типо как deep copy  в питоне

возможно, есть еще варианты, но я пока не придумала :)

2023-12-13 09:59 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (Objects.equals(film.getName(), "")) {
я еще методы с валидацией перенесла в сервис. насколько я поняла из вебинара с наставником, так логичнее сразу сделать, иначе потом все равно придется менять, когда начнем базы данных подключать

2023-12-13 17:28 UTC, Frilock approved these changes
Добрый вечер, душить не буду, принято, работаем дальше

2023-12-14 04:41 UTC, merged