feat: added sql
elenabokhan13/java-filmorate pull request #12
Opened 2023-12-31 14:48 UTC by elenabokhan13

2024-01-10 06:47 UTC, Frilock requested changes
Добрый день, оставил комментарии в коде

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandlers.java
> +    public ErrorResponse mpaNotRegisteredException(final MpaNotFound e) {
Вы для каждой сущности будете делать кастомное исключение на каждую ситуацию? Сделайте одно и передавайте класс. А то если у вас будет 10 сущностей или 100, то это все будет выглядеть не очень

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Validated
Зачем она?

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Validated
Зачем она?

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
А почему бы сразу не проинициализировать? Чтобы потом на нул не проверять

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    SENTREQUEST
Вообще енам из 1го элемента выглядит странно, достаточно было константу сделать в классе и ее использовать. А когда уже будет более 1 значения, можно было бы делать енам

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +public class Mpa {
Полностью одинаковые сущности с Genre, можно попробовать сделать абстракцию или использовать 1 обьект. Попробуйте если есть желание

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Как уже писал, можно попробовать инициализировать сразу. Вы вроде говорили, что тогда у вас не проходят тесты. Это на самом деле странно, если будет желание то можете поразбираться

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new GenreNotFound("Данный жанр не найден.");
Идентификатор пробрасывайте

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getGenres() != null) {
На мой взгляд можно инвертировать условие, тогда этот код можно будет писать без лишней вложенности

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getGenres() != null) {
Аналогично

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                int length = idSet.size();
int length = idSet.size();
                idSet.add(genre.getId());
                int newLength = idSet.size();
                if (length == newLength) {
                    continue;
                }
                
                А это что за странная логика? Если вы туда элемент добавляете, как они равны могут быть?

2024-01-10 06:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        mpas.add("G");
А вот эти значения как раз можно было в енам вынести

2024-01-10 06:47 UTC, Frilock commented on src/main/resources/data.sql
> +INSERT INTO rating_list (rating_name)
Надо проверять что их еще нет

2024-01-10 06:47 UTC, Frilock commented on src/main/resources/schema.sql
> +    name varchar(50),
Эти размеры нужно так же проставлять в аннотации Column в классах модели, чтобы лишний раз в скрипты и БД не лазить
На ваше усмотрение, но в следующих работах обязательно

2024-01-10 06:47 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
А тут IF NOT EXISTS зачем добавлять? Если вы строчкой выше удалили ее

2024-01-10 06:47 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTest.java
> +                "CREATE TABLE IF NOT EXISTS users (\n" +
Есть аннотация для тестов sql, посмотрите как с ней работать (на ваше усмотрение конечно)

2024-01-11 07:22 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandlers.java
> +    public ErrorResponse mpaNotRegisteredException(final MpaNotFound e) {
поправила. меня тоже это смущало, но я была не уверена, можно ли под все сущности одну кастомную ошибку использовать

2024-01-11 07:28 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Validated
удалила теперь. закопипастила и не убрала сразу ((

2024-01-11 07:28 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Validated
удалила теперь. закопипастила и не убрала сразу ((

2024-01-11 07:29 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
фух, теперь разобралась, как валидировать сразу, если использовать @Build и дессериализацию из json

2024-01-11 07:29 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    SENTREQUEST
исправила. тоже была не уверена как лучше в данном случае поступить

2024-01-11 07:30 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +public class Mpa {
сделала один объект, который используется в обоих случаях, мне показалось так проще по восприятию чем через абстракцию

2024-01-11 07:32 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
да-да, теперь разобралась )) проблема в аннотации builder, она не дает делать инициализацию сразу. аннотации builder default и singular не помогали из-за json. но теперь нашла еще аннотацию, которая заставляет джексон сериализировать json через билдер, и тогда все работает :)

2024-01-11 07:32 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new GenreNotFound("Данный жанр не найден.");
+

2024-01-11 07:35 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getGenres() != null) {
согласна. и теперь, когда у меня сразу инициализируются эти списки, мне проверка на нал совсем не нужна

2024-01-11 07:36 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getGenres() != null) {
поправила

2024-01-11 07:40 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                int length = idSet.size();
здесь смысл в том, что жанры должны быть уникальны. поэтому я сделала сет с айдишниками жанров, которые добавляю. если айди пытаться добавить второй раз (когда он уже есть в сете), то он не добавится, в этом случае длина списка не изменится, и они будут равны. значит создавать и добавлять этот объект не нужно. а если длина изменится, значит это уникальный айдишник и его еще не было добавлено ранее.

в универе так часто делаем в питоне для оптимизации кода, если нужно уникальные значения только отфильтровать

2024-01-11 07:42 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        mpas.add("G");
я пыталась, это первое, что пришло мне в голову )))) не получается, потому что некоторые рейтинги написаны через дефис, и такой енам сделать нельзя. а если кастомизировать енам без дефиса, то получается сложно, т.к. чтобы пройти тесты в базу данных и в память для хранения нужно вносить значения с дефисами. проще и понятнее выглядит так, в итоге

2024-01-11 07:42 UTC, elenabokhan13 commented on src/main/resources/data.sql
> +INSERT INTO rating_list (rating_name)
добавила

2024-01-11 07:48 UTC, elenabokhan13 commented on src/main/resources/schema.sql
> +    name varchar(50),
добавила. в общем классе для mps и genres указала максимально допустимое значение (т.е. для genres)

2024-01-11 07:49 UTC, elenabokhan13 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
поправила

2024-01-11 07:49 UTC, elenabokhan13 commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTest.java
> +                "CREATE TABLE IF NOT EXISTS users (\n" +
добавила, очень крутая штука :)

2024-01-12 08:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        mpas.add("G");
Енамы можно делать из нескольких полей, например CAR("машина") и тут можно писать что угодно - с дефисом или без)
а получать потом CAR.getDescription - как пример

2024-01-12 08:13 UTC, Frilock approved these changes
Принято

2024-01-12 10:35 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        mpas.add("G");
спасибо! почитала об этом сейчас дополнительно :)

2024-01-12 10:35 UTC, merged