feat: built User and Film controls
elenabokhan13/java-filmorate pull request #4
Opened 2023-11-29 12:14 UTC by elenabokhan13

2023-11-29 15:05 UTC, Frilock requested changes
Оставил ряд комментариев в коде

2023-11-29 15:05 UTC, Frilock commented on pom.xml
> +            <version>2.8.8</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends Exception {
Наследоваться нужно от RuntimeException, и в конструкторе вызывать super

2023-11-29 15:05 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void contextLoads() {
Данный тест не нужен, поскольку остальные тесты проверят, поднялся ли контекст или нет

2023-11-29 15:05 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        User user1 = User.builder()
Добавление числовых префиксов и окончаний не приветствуется, сделайте под каждый контроллер отдельный тестовый класс, а внутри тесты под каждый конкретный кейс. Не нужно все делать в 1 тесте

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String name;
А почему Имя тут не валидируете?

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else if (user.getBirthday().isAfter(LocalDate.now())) {
Вам так же нужно проверить что дата не равна null, иначе вы NPE получите

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Если все методы контроллера имеют общий маппинг, то его можно вынести в аннотацию класса - RequestMapping(...)

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Не лучше ли использовать для хренния маппу, чтобы было проще выполнять поиск по идентификатору?

2023-11-29 15:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/adapter/DurationAdapter.java
> +public class DurationAdapter implements JsonSerializer<Duration>, JsonDeserializer<Duration> {
А для чего это вам вообще? У вас будет работать и без адапторов)

2023-11-30 07:05 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String name;
у нас в ТЗ ничего не сказано про имя, и в постмен тестах есть тест на создание юзера с пустым именем. когда я добавила сюда валидацию, я перестала проходить все тесты в постмане. поэтому сначала добавила, потом убрала все-таки

2023-11-30 07:13 UTC, elenabokhan13 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String name;
у нас по ТЗ если имя может быть пустым, если оно пустое, то то оно должно равняться логину. если я здесь валидирую имя, то не прохожу тесты по постман

2023-11-30 07:33 UTC, closed without merging

2023-11-30 07:34 UTC, elenabokhan13 commented
Внесла правки в код для нового коммита